### ISSUE TITLE
Align the widgets to proper position

### ISSUE THREAD

**Issue by HVbajoria** [HVbajoria/Miphy#1]
## Proposed feature
The widgets (login form, chat box, music player, memory game, quotes) are not properly aligned and visible. </br>
Please make the necessary changes to align them.

**Comment by garvpatidar04** [comment]
Can you please assign me the issue I like to work on it?

**Comment by garvpatidar04** [comment]
And can I use CSS in place of SASS if you are comfortable with it?

**Comment by HVbajoria** [comment]
Hey @garvpatidar04, 
Yes you may use CSS. It works for me. 
I have assigned the issue. 
Looking forward to see your creativity.
